name: "Setup Node environment"
description: "Setup Node.js environment"
inputs:
  node-version:
    description: Node.js version
    default: "18.x"
runs:
  using: "composite"
  steps:
    - uses: actions/setup-node@v1
      with:
        node-version: ${{ inputs.node-version }}
        cache: "pnpm"
    - run: corepack enable
      shell: bash
    - run: pnpm install --frozen-lockfile
      shell: bash
