name: CI

on:
  pull_request:
    branches:
      - "**"
  push:
    branches:
      - main

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup-node
      - run: pnpm lint
      - name: check code is up to date
        run: git diff --exit-code

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - uses: ./.github/actions/setup-node
      - run: pnpm test
      - name: check code is up to date
        run: git diff --exit-code
      - name: Coveralls
        uses: coverallsapp/github-action@v1.1.2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: packages/protoc-gen-nexus/coverage/lcov.info
          base-path: packages/protoc-gen-nexus

  test-e2e:
    name: E2E Test - Node.js v${{ matrix.node-version }}
    strategy:
      matrix:
        node-version: ["18.x", "20.x"]
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - uses: ./.github/actions/setup-node
        with:
          node-version: ${{ matrix.node-version }}
      - run: pnpm test:e2e
      - name: check code is up to date
        run: git diff --exit-code
